@api = http://localhost:3000
@products = /products

###
GET {{api}}/products

###
POST {{api}}/products
Content-Type: application/json

{
    "name": "microphone",
    "description": "microphone samsing"
}
